/**
 * Tool Layer Types
 *
 * Types related to tool definitions, execution context, and middleware.
 */

import type { Message, MessageContent, ToolCall } from "../domain/model";
import type { ToolMiddleware } from "../domain/tool";

/**
 * Tool output payload for tool-call loop middleware.
 *
 * Framework code will map this payload back to the protocol-level `role: "tool"`
 * message shape using `callId`.
 */
export interface ToolOutput {
  /** Must match the corresponding ToolCall.id */
  callId: string;
  /** Content to send back as the tool result */
  content: MessageContent | null;
}

/**
 * One completed call/output pair inside a tool round.
 */
export interface ToolTurnEntry {
  /** Tool call id */
  callId: string;
  /** Tool name requested by the assistant */
  toolName: string;
  /** Raw arguments generated by the assistant */
  arguments: string;
}

/**
 * Structured history for one completed tool round.
 */
export interface ToolTurn {
  /** Tool call/output pairs from that round */
  entries: readonly ToolTurnEntry[];
}

/**
 * Tool-call loop context.
 *
 * This context is captured after the model has already returned `tool_calls`
 * for the current turn, and before those calls are handed to the real tool
 * executor.
 *
 * Middleware can inspect the prompt-facing inputs and the requested tool calls,
 * but must not mutate them.
 */
export interface ToolCallLoopContext {
  /**
   * 0-based index of the LLM turn that will receive these tool outputs (the prompt loop step
   * after the turn that emitted `originalCalls`).
   */
  readonly step: number;
  /**
   * The live loop conversation the model is about to see (system + instruction + accumulated
   * tool rounds), as fed to `executeTools`. Exposed so a middleware can measure real context
   * occupancy directly instead of maintaining a fragile running tally. Read-only reference (not
   * cloned): middleware must not mutate it. Empty when the loop ran without a forked runtime.
   */
  readonly messages: readonly Message[];
  /**
   * Completed tool rounds from earlier steps.
   *
   * Rejelly constrains the promptAgent turn loop to:
   * 1. system
   * 2. instruction
   * 3. repeated tool-call / tool-result rounds
   * 4. schema-constrained final content
   *
   * This field exposes the structured history from step 3 only. The current
   * round being processed is represented by `originalCalls`, not included here.
   */
  readonly toolTurns: readonly ToolTurn[];
  /** Combined system instruction, if any */
  readonly systemInstruction: string | null;
  /** Flattened task instruction, if any */
  readonly instruction: MessageContent | null;
  /** Original tool calls requested by the model in this turn */
  readonly originalCalls: readonly ToolCall[];
}

/**
 * Tool-call loop middleware interface.
 *
 * This middleware wraps the gap between "assistant produced tool calls" and
 * "tools are actually executed". It can filter calls, short-circuit execution,
 * or synthesize tool outputs, but cannot modify the prompt instruction or
 * schema.
 */
export interface ToolCallLoopMiddleware {
  /** Middleware name (for debugging and logging) */
  name: string;

  /**
   * The middleware handler function.
   *
   * `currentCalls` is the tool-call list passed from the outer layer (or the
   * model's original list on the outermost middleware). Use `next(filteredCalls)`
   * to continue with a modified set, or return early to intercept execution.
   */
  handler: (
    ctx: ToolCallLoopContext,
    currentCalls: ToolCall[],
    next: (calls: ToolCall[]) => Promise<ToolOutput[]>,
  ) => Promise<ToolOutput[]>;

  /** Optional: config snapshot for debugging/dashboard display */
  config?: Record<string, unknown>;
}

/**
 * Options for equipTool
 */
export interface EquipToolOptions {
  /** Dynamic middleware array (contextual, applied per-agent) */
  middleware?: ToolMiddleware[];
}
